CREATE TABLE STUDENT_TBL(
    STUDENT_NAME VARCHAR2(20),
    STUDENT_AGE NUMBER,
    STUDENT_GRADE NUMBER,
    STUDENT_ADDRESS VARCHAR2(100)
);
--수정 -> 삭제 + 생성
--테이블 삭제
--ORA-00942: table or view does not exist
DROP TABLE STUDENT_TBL;

--TABLE에 데이터를 넣는 방법! -> 회원가입
INSERT INTO STUDENT_TBL(STUDENT_NAME, STUDENT_AGE, STUDENT_GRADE, STUDENT_ADDRESS)
VALUES ('일용자', 22, 1, '서울 중구');
--컬럼명 생략 가능!
INSERT INTO STUDENT_TBL VALUES ('이용자', 23, 2, '서울 종로구');

INSERT INTO STUDENT_TBL VALUES('삼용자', 25, 3, '서울 서대문구');

INSERT INTO STUDENT_TBL VALUES('사용자', 44, 4, '서울 동대문구');

INSERT INTO STUDENT_TBL
VALUES(' ', 33, 3, NULL);

UPDATE STUDENT_TBL 
SET STUDENT_AGE = 30
WHERE STUDENT_GRADE = 2;

--데이터를 삭제해보자 -> 회원탈퇴
DELETE FROM STUDENT_TBL;

DELETE FROM STUDENT_TBL
WHERE STUDENT_GRADE = 2;

CREATE TABLE DATATYPE_TBL(
    MOONJJA CHAR(10),  
    --알파벳 10글자, 한글 3글자
    MOONJJAYUL VARCHAR2(100), 
    --알파벳 100글자, 한글 33글자
    SOOJJA NUMBER,
    NALJJA DATE,
    NALJJA2 TIMESTAMP  
);

--데이터 조회
SELECT * 
FROM STUDENT_TBL
--WHERE STUDENT_GRADE = 2;



